AWSTemplateFormatVersion: '2010-09-09'
Description: "Telemetria streaming: API Gateway -> Kinesis -> Lambda -> DynamoDB (Lambda placeholder)."

Parameters:
  ProjectName:
    Type: String
    Default: acdc

  StageName:
    Type: String
    Default: prod

  StreamShardCount:
    Type: Number
    Default: 1
    MinValue: 1

  TrackLengthMeters:
    Type: Number
    Default: 5891

Resources:

  ############################################################
  # Kinesis Stream
  ############################################################
  TelemetryStream:
    Type: AWS::Kinesis::Stream
    Properties:
      Name: !Sub "${ProjectName}-${StageName}-telemetry"
      ShardCount: !Ref StreamShardCount
      RetentionPeriodHours: 24

  ############################################################
  # DynamoDB
  ############################################################
  CarStateTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${ProjectName}-${StageName}-car-state"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: race_id
          AttributeType: S
        - AttributeName: car_id
          AttributeType: N
      KeySchema:
        - AttributeName: race_id
          KeyType: HASH
        - AttributeName: car_id
          KeyType: RANGE
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

  ############################################################
  # API Gateway
  ############################################################
  TelemetryApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Sub "${ProjectName}-${StageName}-telemetry-api"
      EndpointConfiguration:
        Types:
          - REGIONAL

  TelemetryResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref TelemetryApi
      ParentId: !GetAtt TelemetryApi.RootResourceId
      PathPart: telemetry

  ApiGatewayToKinesisRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${ProjectName}-${StageName}-apigw-kinesis-role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: PutRecordToKinesis
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: kinesis:PutRecord
                Resource: !GetAtt TelemetryStream.Arn

  TelemetryPostMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref TelemetryApi
      ResourceId: !Ref TelemetryResource
      HttpMethod: POST
      AuthorizationType: NONE
      Integration:
        Type: AWS
        IntegrationHttpMethod: POST
        Credentials: !GetAtt ApiGatewayToKinesisRole.Arn
        Uri: !Sub "arn:aws:apigateway:${AWS::Region}:kinesis:action/PutRecord"
        PassthroughBehavior: NEVER
        RequestTemplates:
          application/json: !Sub |
            {
              "StreamName": "${TelemetryStream}",
              "PartitionKey": "default",
              "Data": "$util.base64Encode($input.body)"
            }
        IntegrationResponses:
          - StatusCode: 200
            ResponseTemplates:
              application/json: '{"status":"ok"}'
      MethodResponses:
        - StatusCode: 200

  TelemetryDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn: TelemetryPostMethod
    Properties:
      RestApiId: !Ref TelemetryApi

  TelemetryStage:
    Type: AWS::ApiGateway::Stage
    Properties:
      RestApiId: !Ref TelemetryApi
      DeploymentId: !Ref TelemetryDeployment
      StageName: !Ref StageName

  ############################################################
  # Lambda Role
  ############################################################
  LeaderboardLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${ProjectName}-${StageName}-leaderboard-lambda-role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: ReadKinesisWriteDdb
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - kinesis:GetRecords
                  - kinesis:GetShardIterator
                  - kinesis:DescribeStream
                  - kinesis:ListShards
                Resource: !GetAtt TelemetryStream.Arn
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                Resource: !GetAtt CarStateTable.Arn

  ############################################################
  # Lambda Placeholder
  ############################################################
  LeaderboardLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "${ProjectName}-${StageName}-leaderboard"
      Runtime: python3.11
      Handler: index.lambda_handler
      Role: !GetAtt LeaderboardLambdaRole.Arn
      Timeout: 10
      MemorySize: 256
      Code:
        ZipFile: |
          def lambda_handler(event, context):
              print("Placeholder Lambda ejecutada")
              print(event)
              return {"status": "ok"}
      Environment:
        Variables:
          DDB_TABLE: !Ref CarStateTable
          TRACK_LENGTH_M: !Ref TrackLengthMeters

  ############################################################
  # Kinesis -> Lambda
  ############################################################
  KinesisToLambdaMapping:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      EventSourceArn: !GetAtt TelemetryStream.Arn
      FunctionName: !Ref LeaderboardLambda
      StartingPosition: LATEST
      BatchSize: 10
      MaximumBatchingWindowInSeconds: 1
      Enabled: true

Outputs:
  ApiInvokeUrl:
    Value: !Sub "https://${TelemetryApi}.execute-api.${AWS::Region}.amazonaws.com/${StageName}/telemetry"

  StreamName:
    Value: !Ref TelemetryStream

  CarStateTableName:
    Value: !Ref CarStateTable

  LambdaName:
    Value: !Ref LeaderboardLambda
